services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER}
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${DB_CONTAINER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  db_data: