# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Domain\Account\AccountRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\AccountRepository

    App\Domain\Domain\DomainRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\DomainRepository

    App\Infrastructure\Http\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Infrastructure\Monitoring\DoctrineMetricsMiddleware:
        tags:
            - { name: doctrine.middleware }

    Prometheus\Storage\Redis:
        arguments:
            -
                host: redis
                port: 6379

    Prometheus\CollectorRegistry:
        arguments:
            - '@Prometheus\Storage\Redis'
